
model:
  device: mps
  input_dim: 784
  bottleneck_dim: 512
  encoder_hidden_layers: [512, 512,512]
  decoder_hidden_layers: [512,512,512]
  dropout: 0.5
optimizer:
  learning_rate: 1e-3
  weight_decay: 1e-3
